A=input("enter 3x3 or 4x4 :")
if A=="3x3":
    a=int(input("\nenter a number:"))
    b=int(input("enter a number:"))
    c=int(input("enter a number:"))
    d=int(input("enter a number:"))
    e=int(input("enter a number:"))
    f=int(input("enter a number:"))
    g=int(input("enter a number:"))
    h=int(input("enter a number:"))
    i=int(input("enter a number:"))
    def threecross():
        print("\n---------------------------------------")
        print("\nyour entered elements are..\n")
        print('',a,'\t',b,'\t',c,'\n',d,'\t',e,'\t',f,'\n',g,'\t',h,'\t',i)
    def magicsquare():
        print("\n---------------------------------------")
        print("The magic square of entered elements...")
        print('\n','',h,'\t',a,'\t',f)
        print(" ",c,'\t',e,'\t',g)
        print(" ",d,'\t',i,'\t',b)
        print("\nAnswer :",h+a+f)
    threecross()
    magicsquare()
elif A=="4x4":
    a=int(input("\nenter a number:"))
    b=int(input("enter a number:"))
    c=int(input("enter a number:"))
    d=int(input("enter a number:"))
    e=int(input("enter a number:"))
    f=int(input("enter a number:"))
    g=int(input("enter a number:"))
    h=int(input("enter a number:"))
    i=int(input("enter a number:"))
    j=int(input("enter a number:"))
    k=int(input("enter a number:"))
    l=int(input("enter a number:"))
    m=int(input("enter a number:"))
    n=int(input("enter a number:"))
    o=int(input("enter a number:"))
    p=int(input("enter a number:"))
    def fourcross():
        print("\n---------------------------------------")
        print("\nyour entered matrix is..\n")
        print('\n',"",a,'\t',b,'\t',c,'\t',d)
        print('\n',"",e,'\t',f,'\t',g,'\t',h)
        print('\n',"",i,'\t',j,'\t',k,'\t',l)
        print('\n',"",m,'\t',n,'\t',o,'\t',p)
    def magicsquare():
        print("\n---------------------------------------")
        print("The magic square of entered elements...")
        print('\n',"",a,'\t',o,'\t',n,'\t',d)
        print('\n',"",l,'\t',f,'\t',g,'\t',i)
        print('\n',"",h,'\t',j,'\t',k,'\t',e)
        print('\n',"",m,'\t',c,'\t',b,'\t',p)
        print("\nAnswer :",a+o+n+d)
    fourcross()
    magicsquare()
